---
# code: language=ansible
- name: Ntp | Add the OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - configuration
    - package
    - service
    - ntp

- name: Ntp | Installation
  ansible.builtin.include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Ntp | Copy the ntp.conf template file
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: "0664"
  notify:
    - restart ntp
  tags:
    - configuration
    - package
    - ntp

- name: Start/stop ntp service
  ansible.builtin.service:
    name: "{{ ntp_service_name }}"
    state: "{{ ntp_service_state }}"
    enabled: "{{ ntp_service_enabled }}"
    pattern: /ntpd
  tags:
    - service
    - ntp
  when: ansible_service_mgr != "systemd"
