---
# code: language=ansible
galaxy_info:
  author: ericsysmin
  role_name: ntp
  company: Avi Networks
  description: This role enables users to install and configure ntp on their hosts.
  license: MIT
  min_ansible_version: "2.10"
  galaxy_tags:
    - system
    - time
    - ntp
    - centos
    - ubuntu
    - el
    - redhat
dependencies: []
