---
# code: language=ansible
- name: Repo Remi | Include distribution specific variables | {{ ansible_distribution }}
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - vars/{{ ansible_distribution | lower }}.yml
    - vars/default.yml

- name: Repo Remi | Import remi GPG keys.
  block:
    - name: Repo Remi | Import remi GPG keys.
      ansible.builtin.rpm_key:
        key: "{{ remi_repo_gpg_key_url }}"
      loop: "{{ remi_repo_gpg_key_urls }}"
      loop_control:
        loop_var: remi_repo_gpg_key_url
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
  rescue:
    - name: Repo Remi | Ensure curl is present (systems without SNI).
      ansible.builtin.package:
        name: curl
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
    - name: Repo Remi | Download GPG key (systems without SNI). # noqa no-changed-when command-instead-of-module
      ansible.builtin.command: curl -sSL {{ remi_repo_gpg_key_url }} -o /tmp/remi_repo-gpg
    - name: Repo Remi | Add Docker GPG key (systems without SNI). # noqa no-changed-when command-instead-of-module
      ansible.builtin.command: rpm --import  /tmp/remi_repo-gpg
    - name: Repo Remi | Remove docker-gpg from tmp folder
      ansible.builtin.file:
        path: /tmp/remi_repo-gpg
        state: absent

- name: Repo Remi | Install distribution version of Remi Repository | {{ ansible_distribution }}
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
