---
# code: language=ansible

- name: Chrony | Add the OS specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Chrony | Installation
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Chrony | Copy the chrony.conf template file
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: "{{ chrony_config_location }}"
    mode: "0644"
  notify:
    - Chrony | Restart chrony

- name: Chrony | start and enable chrony service
  ansible.builtin.service:
    name: "{{ chrony_service_name }}"
    state: "{{ chrony_service_state }}"
    enabled: "{{ chrony_service_enabled }}"
