---
name: ericsysmin.system.epel
on:
  push:
    paths:
      - roles/epel/**
      - molecule/epel/**
      - .github/workflows/epel.yml
  pull_request:
    paths:
      - roles/epel/**
      - molecule/epel/**
      - .github/workflows/epel.yml
jobs:
  molecule:
    runs-on: ubuntu-latest
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    strategy:
      fail-fast: true
      matrix:
        molecule_distro:
          - { distro: centos-7, command: /usr/sbin/init }
          - { distro: centos-8, command: /usr/sbin/init }
        collection_role:
          - epel
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/ericsysmin/system

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          python -m pip install --upgrade pip
          pip install ansible molecule yamllint ansible-lint docker molecule-docker

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_COMMAND=${{ matrix.molecule_distro.command }}
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test -s ${{ matrix.collection_role }}
