---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Wait for systemd to complete initialization. # noqa command-instead-of-module
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >-
        "running" in systemctl_status.stdout or "degraded" in
        systemctl_status.stdout
      retries: 30
      delay: 5
      when:
        - ansible_service_mgr == "systemd"
        - ansible_distribution == "Fedora"
      changed_when: false
    - name: Update package cache
      ansible.builtin.package:
        update_cache: true
      changed_when: false
      register: task_result
      until: task_result is success
      retries: 10
      delay: 2
  roles:
    - role: ericsysmin.system.chrony
